

// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).


/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated/Ko.ApplicationUser.g.ts" />
/// <reference path="Generated/Ko.ApplicationUserList.g.ts" />
/// <reference path="Generated/Ko.CallSign.g.ts" />
/// <reference path="Generated/Ko.CallSignList.g.ts" />
/// <reference path="Generated/Ko.IpLog.g.ts" />
/// <reference path="Generated/Ko.IpLogList.g.ts" />
/// <reference path="Generated/Ko.LogEntry.g.ts" />
/// <reference path="Generated/Ko.LogEntryList.g.ts" />
/// <reference path="Generated/Ko.RadioIdLog.g.ts" />
/// <reference path="Generated/Ko.RadioIdLogList.g.ts" />
/// <reference path="Generated/Ko.Server.g.ts" />
/// <reference path="Generated/Ko.ServerList.g.ts" />
/// <reference path="Generated/Ko.Stream.g.ts" />
/// <reference path="Generated/Ko.StreamList.g.ts" />
/// <reference path="Generated/Ko.TalkGroup.g.ts" />
/// <reference path="Generated/Ko.TalkGroupList.g.ts" />
/// <reference path="Generated/Ko.VoiceTransmission.g.ts" />
/// <reference path="Generated/Ko.VoiceTransmissionList.g.ts" />
